apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: netray
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongodb8"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mongo-pvc
 namespace: netray
spec:
 storageClassName: local-path
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 50Gi