apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: database
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 32017   # Change here
    protocol: TCP
  selector:
    app: database
