services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq-data:/var/lib/rabbitmq/
        - rabbitmq-log:/var/log/rabbitmq
    networks:
        - rabbitmq-network
    restart: always

volumes:
  rabbitmq-data:
  rabbitmq-log:

networks:
  rabbitmq-network:
    driver: bridge

