apiVersion: v1
kind: Service
metadata:
  name: my-redis-service
  labels:
    app: redis
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 32379
  selector:
    app: redis